// GENERATED by scripts/build-textures.ts — do not edit by hand (re-run `npx tsx scripts/build-textures.ts`).
/**
 * Frame names of the baked texture atlas (public/textures/atlas.json, PixiJS spritesheet, GDD §14.2 / D22).
 * Pixel sizes are at 3× (TEXTURE_SCALE): a nominal 42 dp board cell is a 128 px tile, so draw
 * frames at (size / TEXTURE_SCALE) dp. White frames (sym_*, drop_*, splat_*, stamp_ring, glow_soft,
 * ring_burst) are meant to be tinted; particles and decals have a centred default anchor.
 */

export const ATLAS_JSON = 'textures/atlas.json';
export const PAPER_TEXTURE = 'textures/paper.png';
export const PAPER_TILE_PX = 512;
export const TEXTURE_SCALE = 3;
export const CELL_PX = 128;
export const NOMINAL_CELL_DP = 42;
/** Extruded border around every frame in the atlas page (px). */
export const ATLAS_EXTRUDE = 2;

export const INK_VARIANTS = 4;
export const BLIND_VARIANTS = 2;
export const LEAD_VARIANTS = 2;
export const DROP_COUNT = 6;
export const SPLAT_COUNT = 4;
export const FLECK_COUNT = 4;

export type InkIndex = 0 | 1 | 2 | 3 | 4;
export type InkVariant = 0 | 1 | 2 | 3;
export type BlindVariant = 0 | 1;
export type LeadVariant = 0 | 1;
export type DropIndex = 0 | 1 | 2 | 3 | 4 | 5;
export type SplatIndex = 0 | 1 | 2 | 3;
export type FleckIndex = 0 | 1 | 2 | 3;
export type CardRarity = 'common' | 'rare' | 'legendary';

export const FRAMES = {
  /** Printed type-block cell face (ink k, edge/misregistration variant v). */
  ink: (k: InkIndex, v: InkVariant) => `ink_${k}_${v}` as const,
  /** Highlighted face: line about to print / placement ghost. */
  inkHighlight: (k: InkIndex) => `ink_${k}_hl` as const,
  blind: (v: BlindVariant) => `blind_${v}` as const,
  lead: (v: LeadVariant) => `lead_${v}` as const,
  jam: 'jam',
  cellEmpty: 'cell_empty',
  /** Colour-blind symbol ● ▲ ■ ◆ ✚ (white; tint ink at 55 % or paper on blue). */
  symbol: (k: InkIndex) => `sym_${k}` as const,
  drop: (i: DropIndex) => `drop_${i}` as const,
  splat: (i: SplatIndex) => `splat_${i}` as const,
  fleck: (i: FleckIndex) => `fleck_${i}` as const,
  platen: 'platen',
  stampRing: 'stamp_ring',
  card: (r: CardRarity) => `card_${r}` as const,
  cardEmpty: 'card_empty',
  cardDisabled: 'card_disabled',
  uiPanel: 'ui_panel',
  button: 'btn',
  buttonPressed: 'btn_pressed',
  glowSoft: 'glow_soft',
  ringBurst: 'ring_burst',
} as const;

export const FRAME_NAMES = [
  'ink_0_0',
  'ink_0_1',
  'ink_0_2',
  'ink_0_3',
  'ink_0_hl',
  'ink_1_0',
  'ink_1_1',
  'ink_1_2',
  'ink_1_3',
  'ink_1_hl',
  'ink_2_0',
  'ink_2_1',
  'ink_2_2',
  'ink_2_3',
  'ink_2_hl',
  'ink_3_0',
  'ink_3_1',
  'ink_3_2',
  'ink_3_3',
  'ink_3_hl',
  'ink_4_0',
  'ink_4_1',
  'ink_4_2',
  'ink_4_3',
  'ink_4_hl',
  'blind_0',
  'blind_1',
  'lead_0',
  'lead_1',
  'jam',
  'cell_empty',
  'sym_0',
  'sym_1',
  'sym_2',
  'sym_3',
  'sym_4',
  'drop_0',
  'drop_1',
  'drop_2',
  'drop_3',
  'drop_4',
  'drop_5',
  'splat_0',
  'splat_1',
  'splat_2',
  'splat_3',
  'fleck_0',
  'fleck_1',
  'fleck_2',
  'fleck_3',
  'platen',
  'stamp_ring',
  'card_common',
  'card_rare',
  'card_legendary',
  'card_empty',
  'card_disabled',
  'ui_panel',
  'btn',
  'btn_pressed',
  'glow_soft',
  'ring_burst',
] as const;
export type FrameName = (typeof FRAME_NAMES)[number];

/** Frame sizes in atlas pixels (3×). */
export const FRAME_SIZE: Readonly<Record<FrameName, { readonly w: number; readonly h: number }>> = {
  ink_0_0: { w: 128, h: 128 },
  ink_0_1: { w: 128, h: 128 },
  ink_0_2: { w: 128, h: 128 },
  ink_0_3: { w: 128, h: 128 },
  ink_0_hl: { w: 128, h: 128 },
  ink_1_0: { w: 128, h: 128 },
  ink_1_1: { w: 128, h: 128 },
  ink_1_2: { w: 128, h: 128 },
  ink_1_3: { w: 128, h: 128 },
  ink_1_hl: { w: 128, h: 128 },
  ink_2_0: { w: 128, h: 128 },
  ink_2_1: { w: 128, h: 128 },
  ink_2_2: { w: 128, h: 128 },
  ink_2_3: { w: 128, h: 128 },
  ink_2_hl: { w: 128, h: 128 },
  ink_3_0: { w: 128, h: 128 },
  ink_3_1: { w: 128, h: 128 },
  ink_3_2: { w: 128, h: 128 },
  ink_3_3: { w: 128, h: 128 },
  ink_3_hl: { w: 128, h: 128 },
  ink_4_0: { w: 128, h: 128 },
  ink_4_1: { w: 128, h: 128 },
  ink_4_2: { w: 128, h: 128 },
  ink_4_3: { w: 128, h: 128 },
  ink_4_hl: { w: 128, h: 128 },
  blind_0: { w: 128, h: 128 },
  blind_1: { w: 128, h: 128 },
  lead_0: { w: 128, h: 128 },
  lead_1: { w: 128, h: 128 },
  jam: { w: 128, h: 128 },
  cell_empty: { w: 128, h: 128 },
  sym_0: { w: 56, h: 56 },
  sym_1: { w: 56, h: 56 },
  sym_2: { w: 56, h: 56 },
  sym_3: { w: 56, h: 56 },
  sym_4: { w: 56, h: 56 },
  drop_0: { w: 64, h: 64 },
  drop_1: { w: 80, h: 80 },
  drop_2: { w: 96, h: 96 },
  drop_3: { w: 112, h: 112 },
  drop_4: { w: 128, h: 128 },
  drop_5: { w: 88, h: 88 },
  splat_0: { w: 192, h: 192 },
  splat_1: { w: 224, h: 224 },
  splat_2: { w: 256, h: 256 },
  splat_3: { w: 240, h: 240 },
  fleck_0: { w: 24, h: 24 },
  fleck_1: { w: 32, h: 32 },
  fleck_2: { w: 40, h: 40 },
  fleck_3: { w: 48, h: 48 },
  platen: { w: 1024, h: 96 },
  stamp_ring: { w: 512, h: 192 },
  card_common: { w: 192, h: 240 },
  card_rare: { w: 192, h: 240 },
  card_legendary: { w: 192, h: 240 },
  card_empty: { w: 192, h: 240 },
  card_disabled: { w: 192, h: 240 },
  ui_panel: { w: 256, h: 256 },
  btn: { w: 192, h: 96 },
  btn_pressed: { w: 192, h: 96 },
  glow_soft: { w: 128, h: 128 },
  ring_burst: { w: 256, h: 256 },
};

export interface NineSliceInsets {
  readonly left: number;
  readonly top: number;
  readonly right: number;
  readonly bottom: number;
}

/** 9-slice insets in atlas pixels (also present as Pixi `borders` → texture.defaultBorders). */
export const NINE_SLICE = {
  platen: { left: 64, top: 0, right: 64, bottom: 0 },
  stamp_ring: { left: 52, top: 52, right: 52, bottom: 52 },
  card_common: { left: 36, top: 36, right: 36, bottom: 40 },
  card_rare: { left: 36, top: 36, right: 36, bottom: 40 },
  card_legendary: { left: 36, top: 36, right: 36, bottom: 40 },
  card_empty: { left: 36, top: 36, right: 36, bottom: 40 },
  card_disabled: { left: 36, top: 36, right: 36, bottom: 40 },
  ui_panel: { left: 44, top: 44, right: 44, bottom: 52 },
  btn: { left: 36, top: 34, right: 42, bottom: 44 },
  btn_pressed: { left: 36, top: 34, right: 42, bottom: 44 },
} as const satisfies Partial<Record<FrameName, NineSliceInsets>>;
export type NineSliceFrame = keyof typeof NINE_SLICE;

/** Frames whose default anchor is the centre (0.5, 0.5). */
export const CENTRED_FRAMES: readonly FrameName[] = [
  'sym_0',
  'sym_1',
  'sym_2',
  'sym_3',
  'sym_4',
  'drop_0',
  'drop_1',
  'drop_2',
  'drop_3',
  'drop_4',
  'drop_5',
  'splat_0',
  'splat_1',
  'splat_2',
  'splat_3',
  'fleck_0',
  'fleck_1',
  'fleck_2',
  'fleck_3',
  'platen',
  'stamp_ring',
  'glow_soft',
  'ring_burst',
];

/** Spritesheet animation groups (sheet.animations[group]) for random variant picks. */
export const FRAME_GROUPS = {
  ink_0: 'ink_0',
  ink_1: 'ink_1',
  ink_2: 'ink_2',
  ink_3: 'ink_3',
  ink_4: 'ink_4',
  blind: 'blind',
  lead: 'lead',
  sym: 'sym',
  drop: 'drop',
  splat: 'splat',
  fleck: 'fleck',
} as const;
