/**
 * Bakes PRESS's procedural riso textures (GDD §14.2, decision D22).
 *
 *   npx tsx scripts/build-textures.ts             write public/textures/* and src/render/atlas-frames.ts
 *   npx tsx scripts/build-textures.ts --preview   also write contact sheets to scripts/textures/preview/
 *   npx tsx scripts/build-textures.ts --check     verify the committed outputs are up to date (exit 1 if not)
 *
 * The generator (scripts/textures/gen/**) is bundled with esbuild and run in headless Chromium
 * (Playwright), where it draws every frame per pixel / with Canvas 2D from seeded PRNGs (no
 * Math.random) — so re-running produces byte-identical files. Node packs nothing itself: it only
 * PNG-encodes the raw RGBA it gets back (own deterministic encoder, zlib level 9) and writes the
 * PixiJS spritesheet JSON (hash format) plus typed frame-name constants for the renderer.
 *
 * Outputs (3× of a nominal 42 dp cell → 128 px cell tiles):
 *   public/textures/paper.png    512×512 seamless paper tile (RGB)
 *   public/textures/atlas.png    power-of-two RGBA atlas, 2 px extruded borders
 *   public/textures/atlas.json   PixiJS spritesheet (frames, 9-slice borders, anchors, animations)
 *   src/render/atlas-frames.ts   generated frame-name constants and 9-slice insets
 */
import { chromium } from '@playwright/test';
import { build as esbuild } from 'esbuild';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import * as prettier from 'prettier';
import { encodePng } from './textures/png';
import {
  BLIND_VARIANTS,
  CELL_PX,
  DROP_SIZES,
  EXTRUDE,
  FLECK_SIZES,
  INK_COUNT,
  INK_VARIANTS,
  LEAD_VARIANTS,
  NOMINAL_CELL_DP,
  PAPER_PX,
  SPLAT_SIZES,
  TEXTURE_SCALE,
  frameDefs,
} from './textures/spec';
import type { FrameDef } from './textures/spec';
import type { BuildOptions, BuildOutput } from './textures/gen/main';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT_DIR = resolve(ROOT, 'public/textures');
const FRAMES_TS = resolve(ROOT, 'src/render/atlas-frames.ts');
const PREVIEW_DIR = resolve(ROOT, 'scripts/textures/preview');
const ENTRY = resolve(ROOT, 'scripts/textures/gen/main.ts');
const FONT = resolve(ROOT, 'public/fonts/press-display.otf');

const BUDGET = { atlas: 1.5 * 1024 * 1024, paper: 400 * 1024 };

const args = new Set(process.argv.slice(2));
const PREVIEW = args.has('--preview');
const CHECK = args.has('--check');

async function bundleGenerator(): Promise<string> {
  const r = await esbuild({
    entryPoints: [ENTRY],
    bundle: true,
    format: 'iife',
    globalName: 'PressTextures',
    platform: 'browser',
    target: 'es2022',
    write: false,
    logLevel: 'silent',
  });
  return r.outputFiles[0]!.text;
}

async function runInBrowser(code: string, opts: BuildOptions): Promise<BuildOutput> {
  const browser = await chromium.launch({
    args: ['--disable-gpu', '--force-color-profile=srgb', '--disable-lcd-text', '--font-render-hinting=none'],
  });
  try {
    const page = await browser.newPage();
    page.on('pageerror', (e) => console.error('[page]', e));
    await page.addScriptTag({ content: code });
    return await page.evaluate(
      (o) =>
        (
          globalThis as unknown as { PressTextures: { build: (x: BuildOptions) => Promise<BuildOutput> } }
        ).PressTextures.build(o),
      opts,
    );
  } finally {
    await browser.close();
  }
}

function frameJson(d: FrameDef, x: number, y: number): Record<string, unknown> {
  const out: Record<string, unknown> = {
    frame: { x, y, w: d.w, h: d.h },
    rotated: false,
    trimmed: false,
    spriteSourceSize: { x: 0, y: 0, w: d.w, h: d.h },
    sourceSize: { w: d.w, h: d.h },
  };
  if (d.anchor) out.anchor = d.anchor;
  if (d.borders) out.borders = d.borders;
  return out;
}

function range(n: number): number[] {
  return Array.from({ length: n }, (_, i) => i);
}

function union(n: number): string {
  return range(n).join(' | ');
}

function framesModule(defs: FrameDef[]): string {
  const names = defs.map((d) => `'${d.name}'`).join(', ');
  const sizes = defs.map((d) => `${d.name}: { w: ${d.w}, h: ${d.h} }`).join(', ');
  const nine = defs
    .filter((d) => d.borders)
    .map((d) => {
      const b = d.borders!;
      return `${d.name}: { left: ${b.left}, top: ${b.top}, right: ${b.right}, bottom: ${b.bottom} }`;
    })
    .join(', ');
  const centred = defs
    .filter((d) => d.anchor)
    .map((d) => `'${d.name}'`)
    .join(', ');
  return `// GENERATED by scripts/build-textures.ts — do not edit by hand (re-run \`npx tsx scripts/build-textures.ts\`).
/**
 * Frame names of the baked texture atlas (public/textures/atlas.json, PixiJS spritesheet, GDD §14.2 / D22).
 * Pixel sizes are at ${TEXTURE_SCALE}× (TEXTURE_SCALE): a nominal ${NOMINAL_CELL_DP} dp board cell is a ${CELL_PX} px tile, so draw
 * frames at (size / TEXTURE_SCALE) dp. White frames (sym_*, drop_*, splat_*, stamp_ring, glow_soft,
 * ring_burst) are meant to be tinted; particles and decals have a centred default anchor.
 */

export const ATLAS_JSON = 'textures/atlas.json';
export const PAPER_TEXTURE = 'textures/paper.png';
export const PAPER_TILE_PX = ${PAPER_PX};
export const TEXTURE_SCALE = ${TEXTURE_SCALE};
export const CELL_PX = ${CELL_PX};
export const NOMINAL_CELL_DP = ${NOMINAL_CELL_DP};
/** Extruded border around every frame in the atlas page (px). */
export const ATLAS_EXTRUDE = ${EXTRUDE};

export const INK_VARIANTS = ${INK_VARIANTS};
export const BLIND_VARIANTS = ${BLIND_VARIANTS};
export const LEAD_VARIANTS = ${LEAD_VARIANTS};
export const DROP_COUNT = ${DROP_SIZES.length};
export const SPLAT_COUNT = ${SPLAT_SIZES.length};
export const FLECK_COUNT = ${FLECK_SIZES.length};

export type InkIndex = ${union(INK_COUNT)};
export type InkVariant = ${union(INK_VARIANTS)};
export type BlindVariant = ${union(BLIND_VARIANTS)};
export type LeadVariant = ${union(LEAD_VARIANTS)};
export type DropIndex = ${union(DROP_SIZES.length)};
export type SplatIndex = ${union(SPLAT_SIZES.length)};
export type FleckIndex = ${union(FLECK_SIZES.length)};
export type CardRarity = 'common' | 'rare' | 'legendary';

export const FRAMES = {
  /** Printed type-block cell face (ink k, edge/misregistration variant v). */
  ink: (k: InkIndex, v: InkVariant) => \`ink_\${k}_\${v}\` as const,
  /** Highlighted face: line about to print / placement ghost. */
  inkHighlight: (k: InkIndex) => \`ink_\${k}_hl\` as const,
  blind: (v: BlindVariant) => \`blind_\${v}\` as const,
  lead: (v: LeadVariant) => \`lead_\${v}\` as const,
  jam: 'jam',
  cellEmpty: 'cell_empty',
  /** Colour-blind symbol ● ▲ ■ ◆ ✚ (white; tint ink at 55 % or paper on blue). */
  symbol: (k: InkIndex) => \`sym_\${k}\` as const,
  drop: (i: DropIndex) => \`drop_\${i}\` as const,
  splat: (i: SplatIndex) => \`splat_\${i}\` as const,
  fleck: (i: FleckIndex) => \`fleck_\${i}\` as const,
  platen: 'platen',
  stampRing: 'stamp_ring',
  card: (r: CardRarity) => \`card_\${r}\` as const,
  cardEmpty: 'card_empty',
  cardDisabled: 'card_disabled',
  uiPanel: 'ui_panel',
  button: 'btn',
  buttonPressed: 'btn_pressed',
  glowSoft: 'glow_soft',
  ringBurst: 'ring_burst',
} as const;

export const FRAME_NAMES = [${names}] as const;
export type FrameName = (typeof FRAME_NAMES)[number];

/** Frame sizes in atlas pixels (${TEXTURE_SCALE}×). */
export const FRAME_SIZE: Readonly<Record<FrameName, { readonly w: number; readonly h: number }>> = { ${sizes} };

export interface NineSliceInsets {
  readonly left: number;
  readonly top: number;
  readonly right: number;
  readonly bottom: number;
}

/** 9-slice insets in atlas pixels (also present as Pixi \`borders\` → texture.defaultBorders). */
export const NINE_SLICE = { ${nine} } as const satisfies Partial<Record<FrameName, NineSliceInsets>>;
export type NineSliceFrame = keyof typeof NINE_SLICE;

/** Frames whose default anchor is the centre (0.5, 0.5). */
export const CENTRED_FRAMES: readonly FrameName[] = [${centred}];

/** Spritesheet animation groups (sheet.animations[group]) for random variant picks. */
export const FRAME_GROUPS = {
  ${range(INK_COUNT)
    .map((k) => `ink_${k}: '${`ink_${k}`}'`)
    .join(', ')},
  blind: 'blind',
  lead: 'lead',
  sym: 'sym',
  drop: 'drop',
  splat: 'splat',
  fleck: 'fleck',
} as const;
`;
}

async function format(text: string, file: string): Promise<string> {
  const cfg = (await prettier.resolveConfig(file)) ?? {};
  return prettier.format(text, { ...cfg, filepath: file });
}

function kb(n: number): string {
  return `${(n / 1024).toFixed(1)} KB`;
}

async function main(): Promise<void> {
  const t0 = Date.now();
  const code = await bundleGenerator();
  const fontB64 = PREVIEW && existsSync(FONT) ? readFileSync(FONT).toString('base64') : null;
  const out = await runInBrowser(code, { preview: PREVIEW, fontB64 });
  const tBrowser = Date.now();

  const defs = frameDefs();
  const byName = new Map(out.placements.map((p) => [p.name, p]));
  const frames: Record<string, unknown> = {};
  for (const d of defs) {
    const p = byName.get(d.name);
    if (!p) throw new Error(`frame ${d.name} missing from the atlas`);
    frames[d.name] = frameJson(d, p.x, p.y);
  }
  const groups: Record<string, string[]> = {};
  const group = (key: string, prefix: string, n: number): void => {
    groups[key] = range(n).map((i) => `${prefix}${i}`);
  };
  for (let k = 0; k < INK_COUNT; k++) group(`ink_${k}`, `ink_${k}_`, INK_VARIANTS);
  group('blind', 'blind_', BLIND_VARIANTS);
  group('lead', 'lead_', LEAD_VARIANTS);
  group('sym', 'sym_', INK_COUNT);
  group('drop', 'drop_', DROP_SIZES.length);
  group('splat', 'splat_', SPLAT_SIZES.length);
  group('fleck', 'fleck_', FLECK_SIZES.length);
  const atlasJson = {
    frames,
    animations: groups,
    meta: {
      app: 'PRESS scripts/build-textures.ts',
      version: '1.0',
      image: 'atlas.png',
      format: 'RGBA8888',
      size: { w: out.atlas.w, h: out.atlas.h },
      scale: '1',
    },
  };

  const files = new Map<string, Buffer>();
  const decode = (b64: string): Uint8Array => new Uint8Array(Buffer.from(b64, 'base64'));
  files.set(resolve(OUT_DIR, 'atlas.png'), encodePng(out.atlas.w, out.atlas.h, decode(out.atlas.b64), 4));
  files.set(resolve(OUT_DIR, 'paper.png'), encodePng(out.paper.w, out.paper.h, decode(out.paper.b64), 3));
  const jsonPath = resolve(OUT_DIR, 'atlas.json');
  files.set(jsonPath, Buffer.from(await format(JSON.stringify(atlasJson), jsonPath)));
  files.set(FRAMES_TS, Buffer.from(await format(framesModule(defs), FRAMES_TS)));
  for (const p of out.previews)
    files.set(resolve(PREVIEW_DIR, `${p.name}.png`), encodePng(p.w, p.h, decode(p.b64), 3, 'fast'));

  const atlasSize = files.get(resolve(OUT_DIR, 'atlas.png'))!.length;
  const paperSize = files.get(resolve(OUT_DIR, 'paper.png'))!.length;

  if (CHECK) {
    const stale = [...files.keys()]
      .filter((f) => !f.startsWith(PREVIEW_DIR))
      .filter((f) => !existsSync(f) || !readFileSync(f).equals(files.get(f)!));
    if (stale.length) {
      console.error(
        `Textures are stale: ${stale.map((f) => relative(ROOT, f)).join(', ')}. Run npx tsx scripts/build-textures.ts`,
      );
      process.exit(1);
    }
    console.log('Textures up to date.');
  } else {
    for (const [f, buf] of files) {
      mkdirSync(dirname(f), { recursive: true });
      writeFileSync(f, buf);
    }
  }

  console.log(
    `atlas.png ${out.atlas.w}×${out.atlas.h}, ${defs.length} frames, ${kb(atlasSize)} · paper.png ${out.paper.w}×${out.paper.h}, ${kb(paperSize)}`,
  );
  console.log(
    `browser ${tBrowser - t0} ms (${Object.entries(out.timings)
      .map(([k, v]) => `${k} ${v}`)
      .join(', ')}), encode ${Date.now() - tBrowser} ms`,
  );
  if (PREVIEW)
    console.log(
      `contact sheets → ${relative(ROOT, PREVIEW_DIR)}/{${out.previews.map((p) => p.name).join(',')}}.png`,
    );
  let over = false;
  if (atlasSize > BUDGET.atlas) {
    console.error(`atlas.png over budget: ${kb(atlasSize)} > ${kb(BUDGET.atlas)}`);
    over = true;
  }
  if (paperSize > BUDGET.paper) {
    console.error(`paper.png over budget: ${kb(paperSize)} > ${kb(BUDGET.paper)}`);
    over = true;
  }
  if (over) process.exit(1);
}

await main();
