/**
 * Rasterises the PRESS app icon and logo (src/ui/icons) for the PWA and Android.
 * All artwork is our own SVG authored in code; Chromium (Playwright) does the rendering.
 *
 *   npm run build:icons                     (npx tsx scripts/build-icons.ts)
 *   npx tsx scripts/build-icons.ts --contact=/tmp/press-icons/contact.png
 *
 * Outputs
 *   public/icons/   icon-192.png, icon-512.png, icon-maskable-512.png,
 *                   apple-touch-icon-180.png, favicon-64.png, logo.svg
 *   android-res/    mipmap-{m,h,xh,xxh,xxxh}dpi/ic_launcher{,_round,_foreground}.png,
 *                   mipmap-anydpi-v26/ic_launcher{,_round}.xml, values/ic_launcher_background.xml,
 *                   drawable/ic_launcher_monochrome.xml (VectorDrawable),
 *                   drawable/splash_icon.png (288 px) + density variants for the Android 12 splash.
 *   --contact       a review sheet with every icon at 24 and 56 px (plus greyscale silhouettes).
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium, type Page } from '@playwright/test';
import {
  APP_ICON_BACKGROUND_SVG,
  APP_ICON_FOREGROUND_SVG,
  APP_ICON_MASKABLE_SVG,
  APP_ICON_MONOCHROME_PATH,
  APP_ICON_MONOCHROME_SVG,
  APP_ICON_SVG,
  appIconLegacySvg,
} from '../src/ui/icons/app-icon';
import { LOGO_SVG } from '../src/ui/icons/logo';
import { MODIFIER_ICONS } from '../src/ui/icons/modifiers';
import { PLATE_ICONS } from '../src/ui/icons/plates';
import { UI_ICONS } from '../src/ui/icons/ui';
import type { IconFn } from '../src/ui/icons/kit';
import { PAPER, hex } from '../src/theme';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const PUBLIC_ICONS = join(ROOT, 'public/icons');
const ANDROID = join(ROOT, 'android-res');

/** Android density buckets: launcher icon (48 dp) and adaptive foreground (108 dp) sizes. */
const DENSITIES = [
  ['mdpi', 1],
  ['hdpi', 1.5],
  ['xhdpi', 2],
  ['xxhdpi', 3],
  ['xxxhdpi', 4],
] as const;

function write(path: string, data: string | Buffer): void {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, data);
  console.info(`  ${path.slice(ROOT.length + 1) || path}`);
}

async function rasterise(page: Page, svg: string, size: number): Promise<Buffer> {
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(
    `<!doctype html><html><head><style>html,body{margin:0;padding:0;background:transparent}` +
      `svg{display:block;width:${size}px;height:${size}px}</style></head><body>${svg}</body></html>`,
  );
  return page.screenshot({
    type: 'png',
    omitBackground: true,
    clip: { x: 0, y: 0, width: size, height: size },
  });
}

// ---------------------------------------------------------------------------
// Android XML resources (hand-written templates)
// ---------------------------------------------------------------------------

const ADAPTIVE_ICON_XML = `<?xml version="1.0" encoding="utf-8"?>
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/ic_launcher_background" />
    <foreground android:drawable="@mipmap/ic_launcher_foreground" />
    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />
</adaptive-icon>
`;

const BACKGROUND_COLOR_XML = `<?xml version="1.0" encoding="utf-8"?>
<resources>
    <color name="ic_launcher_background">${hex(PAPER).toUpperCase()}</color>
</resources>
`;

/** Themed-icon layer: the same path data as APP_ICON_MONOCHROME_SVG (108 dp viewport). */
const MONOCHROME_VECTOR_XML = `<?xml version="1.0" encoding="utf-8"?>
<!-- PRESS themed icon (Android 13+): type-sort block with the P knocked out and the
     misregistered second impression. Original artwork, generated by scripts/build-icons.ts
     from APP_ICON_MONOCHROME_PATH in src/ui/icons/app-icon.ts. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
    <path
        android:fillColor="#FF000000"
        android:fillType="evenOdd"
        android:pathData="${APP_ICON_MONOCHROME_PATH}" />
</vector>
`;

// ---------------------------------------------------------------------------
// Contact sheet
// ---------------------------------------------------------------------------

function contactHtml(): string {
  const groups: Array<[string, Record<string, IconFn>]> = [
    ['Plates', PLATE_ICONS],
    ['Modifiers', MODIFIER_ICONS],
    ['UI', UI_ICONS],
  ];
  const sized = (svg: string, px: number) =>
    svg.replace('width="48" height="48"', `width="${px}" height="${px}"`);
  let body = '';
  for (const [name, set] of groups) {
    const entries = Object.entries(set);
    body += `<h2>${name} <small>${entries.length}</small></h2><div class="grid">`;
    for (const [k, f] of entries) {
      body += `<figure>${sized(f(`${k}-l`), 56)}${sized(f(`${k}-s`), 24)}<figcaption>${k}</figcaption></figure>`;
    }
    body += `</div><div class="strip grey">${entries.map(([k, f]) => sized(f(`${k}-g`), 24)).join('')}</div>`;
  }
  const icon = (svg: string, px: number) =>
    svg.replace(/width="\d+" height="\d+"/, `width="${px}" height="${px}"`);
  // A launcher shows the central 72 of the 108 dp adaptive canvas, clipped to its mask shape.
  const launcher = (
    px: number,
    radius: string,
    layers = [APP_ICON_BACKGROUND_SVG, APP_ICON_FOREGROUND_SVG],
    bg = '',
  ) => {
    const full = (px * 108) / 72;
    const layer = (svg: string) =>
      icon(svg, full).replace(
        '<svg ',
        `<svg style="position:absolute;left:${(px - full) / 2}px;top:${(px - full) / 2}px" `,
      );
    return (
      `<div style="position:relative;width:${px}px;height:${px}px;border-radius:${radius};overflow:hidden;${bg}">` +
      `${layers.map(layer).join('')}</div>`
    );
  };
  body +=
    `<h2>Logo</h2><div class="row">${LOGO_SVG({ uid: 'c1' })}<span class="mono">${LOGO_SVG({ mono: true })}</span></div>` +
    `<div class="row">${LOGO_SVG({ uid: 'c2' }).replace('width="600" height="180"', 'width="200" height="60"')}</div>` +
    `<h2>App icon</h2><div class="row">` +
    `<figure>${icon(APP_ICON_SVG, 192)}<figcaption>192</figcaption></figure>` +
    `<figure>${icon(APP_ICON_SVG, 48)}<figcaption>48</figcaption></figure>` +
    `<figure>${launcher(192, '50%')}${launcher(48, '50%')}<figcaption>adaptive, circle mask</figcaption></figure>` +
    `<figure>${launcher(192, '28%')}${launcher(48, '28%')}<figcaption>adaptive, squircle mask</figcaption></figure>` +
    `<figure class="themed">${launcher(192, '50%', [APP_ICON_MONOCHROME_SVG], 'background:#d7e3ff')}` +
    `${launcher(48, '50%', [APP_ICON_MONOCHROME_SVG], 'background:#d7e3ff')}<figcaption>monochrome (themed)</figcaption></figure>` +
    `<figure>${icon(APP_ICON_MASKABLE_SVG, 192)}<figcaption>maskable 80% circle</figcaption></figure>` +
    `<figure>${appIconLegacySvg('square', 96)}${appIconLegacySvg('round', 96)}<figcaption>legacy</figcaption></figure>` +
    `</div>`;
  return `<!doctype html><html><head><style>
      body{margin:0;padding:20px;background:${hex(PAPER)};color:#231f20;font:12px system-ui,sans-serif;width:1360px}
      h2{font-size:15px;margin:18px 0 8px}h2 small{color:#8d8a86;font-weight:400}
      .grid{display:flex;flex-wrap:wrap;gap:6px}
      figure{margin:0;display:flex;flex-wrap:wrap;align-items:flex-end;justify-content:center;gap:8px;
        width:124px;padding:8px 0 6px;border:1px solid #e4dccb;border-radius:6px}
      figcaption{width:100%;text-align:center;font-size:11px}
      .strip{display:flex;flex-wrap:wrap;gap:10px;margin:10px 0 4px;padding:8px;border:1px dashed #d8cfbd}
      .grey{filter:grayscale(1)}
      .row{display:flex;flex-wrap:wrap;align-items:center;gap:16px;margin-bottom:8px}
      .row figure{width:auto;padding:8px 10px}
      .mono{color:#2f6fd6}.mono svg{width:300px;height:90px}
      .themed path{fill:#0b3a8c}
    </style></head><body>${body}</body></html>`;
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const contactArg = process.argv.find((a) => a === '--contact' || a.startsWith('--contact='));
  const browser = await chromium.launch();
  try {
    const page = await browser.newPage({ deviceScaleFactor: 1 });

    if (contactArg) {
      const out = contactArg.includes('=')
        ? resolve(contactArg.slice('--contact='.length))
        : join(tmpdir(), 'press-icons-contact.png');
      await page.setViewportSize({ width: 1400, height: 800 });
      await page.setContent(contactHtml());
      mkdirSync(dirname(out), { recursive: true });
      await page.screenshot({ path: out, fullPage: true });
      console.info(`contact sheet → ${out}`);
      return;
    }

    console.info('PWA icons');
    write(join(PUBLIC_ICONS, 'icon-192.png'), await rasterise(page, APP_ICON_SVG, 192));
    write(join(PUBLIC_ICONS, 'icon-512.png'), await rasterise(page, APP_ICON_SVG, 512));
    write(join(PUBLIC_ICONS, 'icon-maskable-512.png'), await rasterise(page, APP_ICON_MASKABLE_SVG, 512));
    write(join(PUBLIC_ICONS, 'apple-touch-icon-180.png'), await rasterise(page, APP_ICON_SVG, 180));
    write(join(PUBLIC_ICONS, 'favicon-64.png'), await rasterise(page, appIconLegacySvg('square', 64), 64));
    write(join(PUBLIC_ICONS, 'logo.svg'), `${LOGO_SVG({ uid: 'file' })}\n`);

    console.info('Android launcher resources');
    for (const [bucket, k] of DENSITIES) {
      const dir = join(ANDROID, `mipmap-${bucket}`);
      write(join(dir, 'ic_launcher.png'), await rasterise(page, appIconLegacySvg('square', 48 * k), 48 * k));
      write(
        join(dir, 'ic_launcher_round.png'),
        await rasterise(page, appIconLegacySvg('round', 48 * k), 48 * k),
      );
      write(join(dir, 'ic_launcher_foreground.png'), await rasterise(page, APP_ICON_FOREGROUND_SVG, 108 * k));
    }
    write(join(ANDROID, 'mipmap-anydpi-v26/ic_launcher.xml'), ADAPTIVE_ICON_XML);
    write(join(ANDROID, 'mipmap-anydpi-v26/ic_launcher_round.xml'), ADAPTIVE_ICON_XML);
    write(join(ANDROID, 'values/ic_launcher_background.xml'), BACKGROUND_COLOR_XML);
    write(join(ANDROID, 'drawable/ic_launcher_monochrome.xml'), MONOCHROME_VECTOR_XML);

    // Android 12 splash: 288 dp canvas, art inside the central 192 dp circle (foreground art
    // sits within 66/108 of the canvas). drawable/ is the mdpi baseline; denser buckets keep it sharp.
    write(join(ANDROID, 'drawable/splash_icon.png'), await rasterise(page, APP_ICON_FOREGROUND_SVG, 288));
    for (const [bucket, k] of DENSITIES.slice(1)) {
      write(
        join(ANDROID, `drawable-${bucket}/splash_icon.png`),
        await rasterise(page, APP_ICON_FOREGROUND_SVG, 288 * k),
      );
    }
  } finally {
    await browser.close();
  }
}

await main();
